using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Focus.Business.Models;
using Focus.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Focus.Business.Interface
{
    public interface IApplicationDbContext
    {
        DbSet<EmailConfiguration> EmailConfiguration { get; set; }
        DbSet<FinancialYearClosing> FinancialYearClosings { get; set; }
        DbSet<FinancialYearClosingBalance> FinancialYearClosingBalances { get; set; }
        DbSet<FinancialYearSetting> FinancialYearSettings { get; set; }
        DbSet<BomRawProducts> BomRawProducts { get; set; }
        DbSet<BomSaleOrderItems> BomSaleOrderItems { get; set; }
        DbSet<Bom> Boms { get; set; }
        DbSet<ListOrderSetup> ListOrderSetups { get; set; }
        DbSet<ItemsListDisplayOrderSetup> ItemsListDisplayOrderSetup { get; set; }
        DbSet<ItemViewSetupForPrint> ItemViewSetupForPrint { get; set; }
        DbSet<ItemViewSetup> ItemViewSetups { get; set; }
        DbSet<BranchVoucher> BranchVouchers { get; set; }
        DbSet<SyncPushPullRecord> SyncPushPullRecords { get; set; }
        DbSet<TransactionApplicationLog> TransactionApplicationLogs { get; set; }
        DbSet<StockReceivedItems> StockReceivedItems { get; set; }
        DbSet<StockReceived> StockReceived { get; set; }
        DbSet<StockTransfer> StockTransfers { get; set; }
        DbSet<StockTransferItems> StockTransferItems { get; set; }
        DbSet<StockRequestItems> StockRequestItems { get; set; }
        DbSet<StockRequest> StockRequests { get; set; }
        DbSet<BranchItems> BranchItems { get; set; }
        DbSet<BundleOfferBranches> BundleOfferBranches { get; set; }
        DbSet<BranchSetup> BranchSetups { get; set; }
        DbSet<BranchUser> BranchUsers { get; set; }
        DbSet<Branch> Branches { get; set; }
        DbSet<PaymentRefund> PaymentRefunds { get; set; }
        DbSet<CustomerGroup> CustomerGroups { get; set; }
        DbSet<PaymentVoucherItem> PaymentVoucherItems { get; set; }
        DbSet<PromotionOfferItem> PromotionOfferItems { get; set; }
        DbSet<ProductGroup> ProductGroups { get; set; }
        DbSet<DeliveryHoliday> DeliveryHolidays { get; set; }
        DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        DbSet<BranchWisePermission> BranchWisePermissions { get; set; }
        DbSet<CreditNoteItem> CreditNoteItems { get; set; }
        DbSet<CreditNote> CreditNotes { get; set; }
        DbSet<ShiftRunEmployee> ShiftRunEmployees { get; set; }
        DbSet<ShiftRun> ShiftRuns { get; set; }
        DbSet<LedgerTransaction> LedgerTransactions { get; set; }
        DbSet<LedgerAccount> LedgerAccounts { get; set; }
        DbSet<Prefixies> Prefixies { get; set; }
        DbSet<DeliveryChallanReserved> DeliveryChallanReserveds { get; set; }
        DbSet<DeliveryChallanReserverdItem> DeliveryChallanReserverdItems { get; set; }
        DbSet<DeliveryChallan> DeliveryChallans { get; set; }
        DbSet<DeliveryChallanItem> DeliveryChallanItems { get; set; }
        DbSet<ContactPerson> ContactPersons { get; set; }
        DbSet<QuotationTemplate> QuotationTemplates { get; set; }
        DbSet<QuotationTemplateItem> QuotationTemplateItems { get; set; }
        DbSet<MultiUp> MultiUps { get; set; }
        DbSet<MultiUPSLineItem> MultiUPSLineItems { get; set; }
        DbSet<ReparingItem> ReparingItems { get; set; }
        DbSet<ReparingOrder> ReparingOrders { get; set; }
        DbSet<ReparingOrderType> ReparingOrderTypes { get; set; }
        DbSet<Focus.Domain.Entities.ManualAttendance> ManualAttendances { get; set; }
        DbSet<WeekHoliday> WeekHolidays { get; set; }
        DbSet<GuestedHoliday> GuestedHolidays { get; set; }
        DbSet<Holiday> Holidays { get; set; }
        DbSet<GoodReceiveNote> GoodReceives { get; set; }
        DbSet<GoodReceiveNoteItem> GoodReceiveNoteItems { get; set; }
        DbSet<VariationInventoryForReporting> VariationInventoryForReportings { get; set; }
        DbSet<VariationInventory> VariationInventories { get; set; }
        DbSet<SaleSizeAssortment> SaleSizeAssortments { get; set; }
        DbSet<ProductSize> ProductSizes { get; set; }
        DbSet<RecipeAssortment> RecipeAssortments { get; set; }
        DbSet<UserLog> UserLogs { get; set; }
        DbSet<UserDefineFlow> UserDefineFlows { get; set; }
        DbSet<SaleOrderVersion> SaleOrderVersions { get; set; }
        DbSet<ImportExportItem> ImportExportItems { get; set; }
        DbSet<ImportExportType> ImportExportTypes { get; set; }
        DbSet<IssuedTo> Issueds { get; set; }
        DbSet<ChequeBookItem> ChequeBookItems { get; set; }
        DbSet<ChequeBook> ChequeBooks { get; set; }
        DbSet<MonthlyCostItem> MonthlyCostItems { get; set; }
        DbSet<TemporaryCashIssueExpense> TemporaryCashIssueExpenses { get; set; }
        DbSet<TemporaryCashReturn> TemporaryCashReturns { get; set; }
        DbSet<TemporaryCashIssueItem> TemporaryCashIssueItems { get; set; }
        DbSet<TemporaryCashIssue> TemporaryCashIssues { get; set; }
        DbSet<CashRequestUser> CashRequestUsers { get; set; }
        DbSet<TemporaryCashAllocation> TemporaryCashAllocations { get; set; }
        DbSet<TemporaryCashRequestItem> TemporaryCashRequestItems { get; set; }
        DbSet<TemporaryCashRequest> TemporaryCashRequests { get; set; }
        DbSet<RunPayrollSalaryDetail> RunPayrollSalaryDetails { get; set; }
        DbSet<RunPayrollDetail> RunPayrollDetails { get; set; }
        DbSet<RunPayroll> RunPayrolls { get; set; }
        DbSet<EmployeeSalaryDetail> EmployeeSalaryDetails { get; set; }
        DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        DbSet<SalaryTaxSlab> SalaryTaxSlabs { get; set; }
        DbSet<TaxSalary> TaxSalaries { get; set; }
        DbSet<LoanPay> LoanPays { get; set; }
        DbSet<LoanPayment> LoanPayments { get; set; }
        DbSet<PaySchedule> PaySchedules { get; set; }
        DbSet<SalaryTemplate> SalaryTemplates { get; set; }
        DbSet<SalaryContribution> SalaryContributions { get; set; }
        DbSet<SalaryAllowance> SalaryAllowances { get; set; }
        DbSet<SalaryDeduction> SalaryDeductions { get; set; }
        DbSet<Deduction> Deductions { get; set; }
        DbSet<Contribution> Contributions { get; set; }
        DbSet<Allowance> Allowances { get; set; }
        DbSet<AllowanceType> AllowanceTypes { get; set; }
        DbSet<GatePass> GatePasses { get; set; }
        DbSet<GatePassItem> GatePassItems { get; set; }
        DbSet<ContractorItem> ContractorItems { get; set; }
        DbSet<ContractorPayment> ContractorPayments { get; set; }
        DbSet<SampleRequestItem> SampleRequestItems { get; set; }
        DbSet<SampleRequest> SampleRequests { get; set; }
        DbSet<BatchCosting> BatchCostings { get; set; }
        DbSet<BatchCostingItem> BatchCostingItems { get; set; }
        DbSet<BatchProcessContractor> BatchProcessContractors { get; set; }
        DbSet<Process> Processes { get; set; }
        DbSet<BatchProcess> BatchProcesses { get; set; }
        DbSet<ProcessItem> ProcessItems { get; set; }
        DbSet<Contractor> Contractors { get; set; }
        DbSet<ProcessContractor> ProcessContractors { get; set; }
        DbSet<PrintOption> PrintOptions { get; set; }
        DbSet<PriceRecord> PriceRecords { get; set; }
        DbSet<PriceLabeling> PriceLabelings { get; set; }
        DbSet<DailyExpenseAttachment> DailyExpenseAttachments { get; set; }
        DbSet<Logistic> Logistics { get; set; }
        DbSet<CompanyOption> CompanyOptions { get; set; }
        DbSet<SaleInvoiceDiscount> SaleInvoiceDiscounts { get; set; }
        DbSet<Discount> Discounts { get; set; }
        DbSet<PurchaseBill> PurchaseBills { get; set; }
        DbSet<PurchaseBillItem> PurchaseBillItems { get; set; }
        DbSet<BillAttachment> BillAttachments { get; set; }
        DbSet<SaleInvoiceAdvancePayment> SaleInvoiceAdvancePayments { get; set; }
        DbSet<PaymentVoucherAttachment> PaymentVoucherAttachments { get; set; }
        DbSet<ProductMaster> ProductMasters { get; set; }
        DbSet<BankPosTerminal> BankPosTerminals { get; set; }
        DbSet<PrintSetting> PrintSettings { get; set; }
        DbSet<TransferHistory> TransferHistories { get; set; }
        DbSet<InventoryBlind> InventoryBlinds { get; set; }
        DbSet<InventoryBlindDetail> InventoryBlindDetails { get; set; }
        DbSet<LoginHistory> LoginHistories { get; set; }
        DbSet<ProductionStockTransfer> ProductionStockTransfers { get; set; }
        DbSet<ProductionBatchItem> ProductionBatchItems { get; set; }
        DbSet<ProductionBatch> ProductionBatchs { get; set; }
        DbSet<RecipeNo> RecipeNos { get; set; }
        DbSet<RecipeItem> RecipeItems { get; set; }
        DbSet<SaleOrder> SaleOrders { get; set; }
        DbSet<SaleOrderItem> SaleOrderItems { get; set; }
        DbSet<ModulesRights> ModulesRights { get; set; }
        DbSet<City> Cities { get; set; }
        DbSet<Region> Regions { get; set; }
        DbSet<ModulesName> ModulesNames { get; set; }
        DbSet<RolesPermissions> RolesPermissions { get; set; }
        DbSet<NobleRoles> NobleRoles { get; set; }
        DbSet<NobleUserRoles> NobleUserRoles { get; set; }
        DbSet<CompanyAccountSetup> CompanyAccountSetups { get; set; }
        DbSet<MobileOrderItem> MobileOrderItems { get; set; }
        DbSet<MobileOrder> MobileOrders { get; set; }
        DbSet<Bank> Banks { get; set; }
        DbSet<DailyExpense> DailyExpenses { get; set; }
        DbSet<DailyExpenseDetail> DailyExpenseDetails { get; set; }
        DbSet<StockAdjustment> StockAdjustments { get; set; }
        DbSet<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }
        DbSet<PaymentVoucher> PaymentVouchers { get; set; }
        DbSet<PaymentVoucherDetail> PaymentVoucherDetails { get; set; }
        DbSet<MonthlyCost> MonthlyCosts { get; set; }
        DbSet<LoginPermissions> LoginPermissions { get; set; }
        DbSet<JournalVoucher> JournalVouchers { get; set; }
        DbSet<JournalVoucherItem> JournalVoucherItems { get; set; }
        DbSet<EmployeeRegistration> EmployeeRegistrations { get; set; }
        DbSet<BundleCategory> BundleCategories { get; set; }
        DbSet<PaymentOption> PaymentOptions { get; set; }
        DbSet<Currency> Currencies { get; set; }
        DbSet<PromotionOffer> PromotionOffers { get; set; }
        DbSet<Terminal> Terminals { get; set; }
        DbSet<DayStart> DayStarts { get; set; }
        DbSet<TaxRate> TaxRates { get; set; }
        DbSet<Origin> Origins { get; set; }
        DbSet<Color> Colors { get; set; }
        DbSet<Size> Sizes { get; set; }
        DbSet<Company> Companies { get; set; }
        DbSet<Contact> Contacts { get; set; }
        DbSet<Unit> Units { get; set; }
        DbSet<ContactAttachment> ContactAttachments { get; set; }
        DbSet<ContactBankAccount> ContactBankAccounts { get; set; }
        DbSet<CompanyInformation> companyInformations { get; set; }
        DbSet<Zone> Zones { get; set; }
        DbSet<CustomerDiscount> CustomerDiscount { get; set; }
        DbSet<Employee> Employees { get; set; }
        DbSet<Department> Departments { get; set; }
        DbSet<EmployeeDepartment> EmployeeDepartments { get; set; }
        DbSet<Designation> Designations { get; set; }
        DbSet<Transporter> Transporters { get; set; }
        DbSet<Attachment> Attachments { get; set; }
        DbSet<EmployeeAttachment> EmployeeAttachments { get; set; }
        DbSet<AccountTemplate> AccountTemplates { get; set; }
        DbSet<Account> Accounts { get; set; }
        DbSet<CostCenter> CostCenters { get; set; }
        DbSet<AccountType> AccountTypes { get; set; }
        DbSet<AccountsLevelOne> AccountsLevelOne { get; set; }
        DbSet<AccountsLevelTwo> AccountsLevelTwo { get; set; }
        DbSet<Warehouse> Warehouses { get; set; }
        DbSet<Brand> Brands { get; set; }
        DbSet<Category> Categories { get; set; }
        DbSet<SubCategory> SubCategories { get; set; }
        DbSet<Product> Products { get; set; }
        DbSet<Purchase> Purchases { get; set; }
        DbSet<PurchaseItem> PurchaseItems { get; set; }
        DbSet<PurchasePost> PurchasePosts { get; set; }
        DbSet<PurchasePostItem> PurchasePostItems { get; set; }
        DbSet<Inventory> Inventories { get; set; }
        DbSet<Stock> Stocks { get; set; }
        DbSet<Transaction> Transactions { get; set; }

        DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        DbSet<CompanyLicence> CompanyLicences { get; set; }
        DbSet<Sale> Sales { get; set; }
        DbSet<SaleItem> SaleItems { get; set; }
        DbSet<SalePayment> SalePayments { get; set; }
        DbSet<UserTerminal> UserTerminals { get; set; }
        DbSet<CashCustomer> CashCustomer { get; set; }
        DbSet<WareHouseTransfer> WareHouseTransfers { get; set; }
        DbSet<WareHouseTransferItem> WareHouseTransferItems { get; set; }
        DbSet<NobleGroup> NobleGroups { get; set; }
        DbSet<NobleModule> NobleModules { get; set; }
        DbSet<Focus.Domain.Entities.NoblePermission> NoblePermissions { get; set; }
        DbSet<CompanyPermission> CompanyPermissions { get; set; }
        DbSet<NobleRolePermission> NobleRolePermissions { get; set; }
        DbSet<CompanyAttachment> CompanyAttachments { get; set; }
        DbSet<EmployeeRegistrationAttachment> EmployeeRegistrationAttachments { get; set; }
        DbSet<OtherCurrency> OtherCurrencies { get; set; }
        DbSet<PurchaseAttachment> PurchaseAttachments { get; set; }
        DbSet<DispatchNote> DispatchNotes { get; set; }
        DbSet<DispatchNoteItem> DispatchNoteItems { get; set; }
        DbSet<DenominationSetup> DenominationSetups { get; set; }
        DbSet<SyncRecord> SyncRecords { get; set; }
        DbSet<CashVoucher> CashVouchers { get; set; }
        DbSet<CompanyProcess> CompanyProcess { get; set; }
        DbSet<PurchaseOrderAction> PurchaseOrderActions { get; set; }
        DbSet<PurchaseInvoiceAttachment> PurchaseInvoiceAttachments { get; set; }
        DbSet<PurchaseInvoiceAction> PurchaseInvoiceActions { get; set; }
        DbSet<PurchaseOrderPayment> PurchaseOrderPayments { get; set; }
        DbSet<ExpenseType> ExpenseTypes { get; set; }
        DbSet<SaleOrderPayment> SaleOrderPayments { get; set; }
        DbSet<ApplicationUpdate> ApplicationUpdates { get; set; }
        DbSet<YearlyPeriod> YearlyPeriods { get; set; }
        DbSet<CompanySubmissionPeriod> CompanySubmissionPeriods { get; set; }
        DbSet<PurchaseOrderExpense> PurchaseOrderExpenses { get; set; }
        DbSet<PurchaseOrderVersion> PurchaseOrderVersions { get; set; }
        DbSet<PurchasePostExpense> PurchasePostExpenses { get; set; }
        DbSet<TerminalCategory> TerminalCategories { get; set; }
        DbSet<WarrantyType> WarrantyTypes { get; set; }
        DbSet<AutoPurchaseSetting> AutoPurchaseSettings { get; set; }
        DbSet<AutoPurchaseTemplate> AutoPurchaseTemplates { get; set; }
        DbSet<AutoPurchaseTemplateItem> AutoPurchaseTemplateItems { get; set; }
        DbSet<PaymentLimit> PaymentLimits { get; set; }

        DbSet<MediaType> MediaTypes { get; set; }
        DbSet<Inquiry> Inquiries { get; set; }
        DbSet<InquiryItem> InquiryItems { get; set; }
        DbSet<InquiryProcess> InquiryProcesses { get; set; }
        DbSet<InquiryModule> InquiryModules { get; set; }
        DbSet<ModuleQuestion> ModuleQuestions { get; set; }
        DbSet<InquiryModuleQuestion> InquiryModuleQuestions { get; set; }
        DbSet<InquiryType> InquiryTypes { get; set; }
        DbSet<InquiryComment> InquiryComments { get; set; }
        DbSet<InquiryMeeting> InquiryMeetings { get; set; }
        DbSet<InquiryMeetingAttendant> InquiryMeetingAttendants { get; set; }
        DbSet<InquiryEmail> InquiryEmails { get; set; }
        DbSet<InquiryEmailCc> InquiryEmailCcs { get; set; }
        DbSet<InquiryStatus> InquiryStatuses { get; set; }
        DbSet<WhiteLabeling> WhiteLabelings { get; set; }
        DbSet<InquiryPriority> InquiryPriorities { get; set; }
        DbSet<InquiryStatusDynamic> InquiryStatusDynamics { get; set; }
        DbSet<DiscountSetup> DiscountSetups { get; set; }
        DbSet<DefaultSetting> DefaultSettings { get; set; }
        DbSet<GsmSmsSetup> GsmSmsSetups { get; set; }
        DbSet<CompanyHolidays> CompanyHolidays { get; set; }
        DbSet<ShiftAssign> ShiftAssigns { get; set; }
        DbSet<ShiftEmployeeAssign> ShiftEmployeeAssigns { get; set; }
        DbSet<LeaveTypes> LeaveTypes { get; set; }
        DbSet<LeavePeriod> LeavePeriods { get; set; }
        DbSet<WorkWeek> WorkWeeks { get; set; }
        DbSet<LeaveHoliday> LeaveHolidays { get; set; }
        DbSet<LeaveRules> LeaveRules { get; set; }
        DbSet<PaidTimeOff> PaidTimeOffs { get; set; }
        DbSet<LeaveGroup> LeaveGroups { get; set; }
        DbSet<LeaveGroupEmployee> LeaveGroupEmployees { get; set; }
        DbSet<ApprovalSystem> ApprovalSystems { get; set; }
        DbSet<ApprovalSystemEmployees> ApprovalSystemEmployees { get; set; }
        DbSet<HoldSetup> HoldSetups { get; set; }
        DbSet<InvoiceDefault> InvoiceDefaults { get; set; }
        DbSet<PermanentDeleteHoldSetup> PermanentDeleteHoldSetups { get; set; }

        bool DisableTenantFilter { get; set; }
      //  void LogTrackedEntities();
        int SaveChanges();
        int SaveChangesAfter();
   
        void SetModified(object entity, string attribute, Guid value);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken());
        public List<SyncRecordModel> SyncLog();

    }
}
